# Using Random Forest for Regression

In [8]:
import pandas as pd
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

#----------------Download File of .csv ---------------#
# https://drive.google.com/file/d/1mVmGNx6cbfvRHC_DvF12ZL3wGLSHD9f_/view
#-----------------------------------------------------#
# The upload file from your system to use this mathod.
# It is posible for Colaboratory Online.
from google.colab import files
uploaded = files.upload()

import io
dataset = pd.read_csv(io.BytesIO(uploaded['petrol_consumption.csv']))
# Here Soper.csv your file name.
#-----------------------------------------------------#

# dataset = pd.read_csv('D:\Datasets\petrol_consumption.csv')
# This for System Software like to be Pycharm.

dataset.head()

Saving petrol_consumption.csv to petrol_consumption.csv


Petrol_tax  Average_income  ...  Population_Driver_licence(%)  Petrol_Consumption
0         9.0            3571  ...                         0.525                 541
1         9.0            4092  ...                         0.572                 524
2         9.0            3865  ...                         0.580                 561
3         7.5            4870  ...                         0.529                 414
4         8.0            4399  ...                         0.544                 410

[5 rows x 5 columns]

In [9]:
import pandas as pd
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

#----------------Download File of .csv ---------------#
# https://drive.google.com/file/d/1mVmGNx6cbfvRHC_DvF12ZL3wGLSHD9f_/view
#-----------------------------------------------------#
# The upload file from your system to use this mathod.
# It is posible for Colaboratory Online.
from google.colab import files
uploaded = files.upload()

import io
dataset = pd.read_csv(io.BytesIO(uploaded['petrol_consumption.csv']))
# Here Soper.csv your file name.
#-----------------------------------------------------#

# dataset = pd.read_csv('D:\Datasets\petrol_consumption.csv')
# This for System Software like to be Pycharm.

# Preparing Data For Training
X = dataset.iloc[:, 0:4].values
y = dataset.iloc[:, 4].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train,'\n\n',y_train)
print(X_test,'\n\n',y_test)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

# Training the Algorithm
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(y_pred)

Saving petrol_consumption.csv to petrol_consumption (1).csv
[[7.5000e+00 5.1260e+03 1.4186e+04 5.2500e-01]
 [7.0000e+00 3.3330e+03 6.5940e+03 5.1300e-01]
 [7.5000e+00 3.3570e+03 4.1210e+03 5.4700e-01]
 [7.5000e+00 3.8460e+03 9.0610e+03 5.7900e-01]
 [7.0000e+00 5.0020e+03 9.7940e+03 5.9300e-01]
 [9.0000e+00 3.8650e+03 1.5860e+03 5.8000e-01]
 [7.0000e+00 4.2960e+03 4.0830e+03 6.2300e-01]
 [7.0000e+00 4.7160e+03 5.9150e+03 7.2400e-01]
 [7.0000e+00 4.3180e+03 1.0340e+04 5.8600e-01]
 [8.0000e+00 4.1880e+03 5.9750e+03 5.6300e-01]
 [9.0000e+00 4.8970e+03 2.4490e+03 5.1100e-01]
 [7.0000e+00 4.2060e+03 8.5080e+03 5.7200e-01]
 [7.0000e+00 3.6560e+03 3.9850e+03 5.6300e-01]
 [7.0000e+00 4.5930e+03 7.8340e+03 6.6300e-01]
 [7.0000e+00 4.3000e+03 3.6350e+03 6.0300e-01]
 [8.0000e+00 4.4470e+03 8.5770e+03 5.2900e-01]
 [7.0000e+00 4.2070e+03 6.5800e+03 5.4500e-01]
 [9.0000e+00 3.7210e+03 4.7460e+03 5.4400e-01]
 [1.0000e+01 5.3420e+03 1.3330e+03 5.7100e-01]
 [7.0000e+00 3.7180e+03 4.7250e+03 5.4000e-01]


# Using Random Forest for Classification

In [7]:
import pandas as pd
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

#----------------Download File of .csv ---------------#
# https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
#-----------------------------------------------------#
# The upload file from your system to use this mathod.
# It is posible for Colaboratory Online.
from google.colab import files
uploaded = files.upload()

import io
dataset = pd.read_csv(io.BytesIO(uploaded['bill_authentication.csv']))
# Here Soper.csv your file name.
#-----------------------------------------------------#

# dataset = pd.read_csv("D:/Datasets/bill_authentication.csv")
# This for System Software like to be Pycharm.

dataset.head()

Saving bill_authentication.csv to bill_authentication (6).csv


Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [6]:
import pandas as pd
import numpy as np
import seaborn as sns #visualisation
import matplotlib.pyplot as plt #visualisation
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor

#----------------Download File of .csv ---------------#
# https://drive.google.com/file/d/13nw-uRXPY8XIZQxKRNZ3yYlho-CYm_Qt/view
#-----------------------------------------------------#
# The upload file from your system to use this mathod.
# It is posible for Colaboratory Online.
from google.colab import files
uploaded = files.upload()

import io
dataset = pd.read_csv(io.BytesIO(uploaded['bill_authentication.csv']))
# Here Soper.csv your file name.
#-----------------------------------------------------#

# dataset = pd.read_csv("D:/Datasets/bill_authentication.csv")
# This for System Software like to be Pycharm.

# Preparing Data For Training
X = dataset.iloc[:, 0:4].values
y = dataset.iloc[:, 4].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)
print(X_train,'\n\n',y_train)
print(X_test,'\n\n',y_test)

# Feature Scaling
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)
print(X_train)
print(X_test)

# Training the Algorithm
regressor = RandomForestRegressor(n_estimators=20, random_state=0)
regressor.fit(X_train, y_train)
y_pred = regressor.predict(X_test)
print(y_pred)


Saving bill_authentication.csv to bill_authentication (5).csv
[[-1.2943    2.6735   -0.84085  -2.0323  ]
 [-0.40857   3.0977   -2.9607   -2.6892  ]
 [-1.5228   -6.4789    5.7568    0.87325 ]
 ...
 [ 0.6005    0.99945  -2.2126    0.097399]
 [ 2.0165   -0.25246   5.1707    1.0763  ]
 [-2.0759   10.8223    2.6439   -4.837   ]] 

 [1 1 1 ... 1 0 0]
[[ -1.7713   -10.7665    10.2184    -1.0043  ]
 [  5.1321    -0.031048   0.32616    1.1151  ]
 [ -2.0149     3.6874    -1.9385    -3.8918  ]
 ...
 [ -2.1652     3.0211    -2.4132    -2.4241  ]
 [  0.48797    3.5674    -4.3882    -3.8116  ]
 [ -4.3667     6.0692     0.57208   -5.4668  ]] 

 [1 0 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 1 0 1 1 1 0 0
 1 0 1 0 1 0 0 1 1 0 0 1 0 0 1 0 1 1 0 1 1 0 1 1 0 0 0 0 1 1 1 1 0 1 0 1 0
 0 1 0 0 0 0 1 1 0 0 1 1 0 0 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 1 0 1 1 1 0
 1 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 1 1 0 0 1 0
 0 1 0 0 0 0 1 0 1 0 1 0 0 1 0 1 0 1 1 0 1 1 0 1 1 1 1 0 0 0 1